
# database connection info
# note: if spaces in password use \, e.g.: my\ password 
# e.g., set host address: cps-postgresql.gonzaga.edu
host=host_address
user=your_username
password=your_password
database=your_database
